version: '3.8'

services:
  persist-linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
    container_name: persist-linux
    hostname: linux-target
    networks:
      persist-net:
        ipv4_address: 10.0.5.10
    volumes:
      - ./solutions:/solutions:ro
      - ./scripts:/scripts:ro
    stdin_open: true
    tty: true
    cap_add:
      - ALL

networks:
  persist-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
