FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y \
    nmap \
    netcat-openbsd \
    sqlmap \
    ffuf \
    nikto \
    curl \
    wget \
    python3 \
    python3-pip \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash student && \
    echo "student:student123" | chpasswd

WORKDIR /home/student

ENV PS1='\[\033[1;35m\][\u@webapp \W]\$\[\033[0m\] '

CMD ["/bin/bash"]
