[global]
    workgroup = CORP
    server string = Workstation
    security = user
    map to guest = bad user
    log file = /var/log/samba/log.%m
    max log size = 1000

[user-profiles]
    path = /data/user-profiles
    browsable = yes
    read only = no
    guest ok = no
