FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y \
    nmap \
    netcat-openbsd \
    curl \
    wget \
    git \
    python3 \
    python3-pip \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Install Nuclei
RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest 2>/dev/null || \
    (wget -q https://github.com/projectdiscovery/nuclei/releases/download/v3.1.0/nuclei_3.1.0_linux_amd64.zip && \
    unzip nuclei_3.1.0_linux_amd64.zip -d /usr/local/bin/ && rm -f nuclei_*.zip)

# Install searchsploit (exploit-db)
RUN git clone --depth 1 https://gitlab.com/exploit-database/exploitdb.git /opt/exploitdb 2>/dev/null && \
    ln -sf /opt/exploitdb/searchsploit /usr/local/bin/searchsploit || \
    apt-get update && apt-get install -y exploitdb

RUN useradd -m -s /bin/bash student && \
    echo "student:student123" | chpasswd

WORKDIR /home/student

ENV PS1='\[\033[1;33m\][\u@vulnscan \W]\$\[\033[0m\] '

CMD ["/bin/bash"]
