FROM kalilinux/kali-rolling

RUN apt-get update && apt-get install -y \
    nmap \
    netcat-openbsd \
    wireshark-common \
    tcpdump \
    dnsutils \
    whois \
    curl \
    wget \
    net-tools \
    iputils-ping \
    nikto \
    dirb \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash student && \
    echo "student:student123" | chpasswd

COPY scripts/ /home/student/scripts/
RUN chmod +x /home/student/scripts/*

WORKDIR /home/student

ENV PS1='\[\033[1;32m\][\u@recon \W]\$\[\033[0m\] '

CMD ["/bin/bash"]
